In [3]:
!python --version

Python 3.9.16


In [4]:
import tensorflow as tf

## Range function in TensorFlow

In [5]:
x = tf.range(12, dtype=tf.float32)
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

## Size of a tensorflow variable

In [6]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

## Reshape a Tensor

In [7]:
X = tf.reshape(x, (3,4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [8]:
tf.size(X)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

## Defining Tensor with all zeroes

In [9]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

## Defining tensor with all Ones

In [10]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

## Tensor with random numbers such that their mean is 0 and std is 1. (Elements drawn from a Standard Gaussian-normal distribution)

In [11]:
tf.random.normal(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.4264909 , -0.1927008 ,  0.7765758 ,  1.0062798 ],
       [ 0.8987102 ,  0.5995608 ,  0.65661615,  0.99199134],
       [ 0.0985158 , -0.14986642, -1.0047174 , -0.09554902]],
      dtype=float32)>

## Constant Tensor

In [12]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

## Indexing and Slicing

In [13]:
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [14]:
X[-1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>

In [15]:
X[0]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [16]:
X[1:3]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [17]:
X[1:]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## Tensors vs Variables in TensorFlow
Tensors in TensorFlow are immutable, and cannot be assigned to. 

Variables in TensorFlow are mutable containers of state that support assignments. 
1. Keep in mind that gradients in TensorFlow do not flow backwards through Variable assignments.
2. Beyond assigning a value to the entire Variable, we can write elements of a Variable by specifying indices.

In [18]:
X_var = tf.Variable(X)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [19]:
X_var[1,2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

##### Assign values to multiple elements in a Tensor Variable

In [20]:
X_var[:2,:].assign(tf.ones(X_var[:2,:].shape, dtype=tf.float32)*12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [21]:
X_var[:2,:].shape

TensorShape([2, 4])

In [22]:
def my_func(a=[]):
    a.append(1)
    return a

print(f"{id(my_func())} {id(my_func())}")
print(my_func())

2539824388800 2539824388800
[1, 1, 1]


In [23]:
print(my_func())

[1, 1, 1, 1]


## Operations

##### Elementwise operations

In [24]:
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

##### Unary scalar operators (taking one input) by the signature <math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>f</mi>
  <mo>:</mo>
  <mrow data-mjx-texclass="ORD">
    <mi mathvariant="double-struck">R</mi>
  </mrow>
  <mo stretchy="false">&#x2192;</mo>
  <mrow data-mjx-texclass="ORD">
    <mi mathvariant="double-struck">R</mi>
  </mrow>
</math>


This just means that the function maps from any real number onto some other real number. Most standard operators can be applied elementwise including unary operators like e^x

In [25]:
tf.exp(x)

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([1.0000000e+00, 2.7182817e+00, 7.3890562e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342877e+02, 1.0966332e+03,
       2.9809580e+03, 8.1030835e+03, 2.2026465e+04, 5.9874141e+04],
      dtype=float32)>

##### Binary scalar operators, which map pairs of real numbers to a (single) real number via the signature <math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>f</mi>
  <mo>:</mo>
  <mrow data-mjx-texclass="ORD">
    <mi mathvariant="double-struck">R</mi>
  </mrow>
  <mo>,</mo>
  <mrow data-mjx-texclass="ORD">
    <mi mathvariant="double-struck">R</mi>
  </mrow>
  <mo stretchy="false">&#x2192;</mo>
  <mrow data-mjx-texclass="ORD">
    <mi mathvariant="double-struck">R</mi>
  </mrow>
</math>

In [26]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x,y,x+y, x-y, x*y, x/y, x**y, y**x

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 4., 8.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 2., 2., 2.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([  2.,   4.,  16., 256.], dtype=float32)>)

## Conacatenating Tensors

In [27]:
X = tf.reshape(tf.range(12, dtype=tf.float32),(3,4))

Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y, tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>)

In [28]:
tf.reduce_sum(X), tf.reduce_sum(Y)

(<tf.Tensor: shape=(), dtype=float32, numpy=66.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.0>)

In [29]:
tf.reduce_prod(X), tf.reduce_prod(Y)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=13824.0>)

## Broadcasting

In [30]:
a = tf.reshape(tf.range(3), (3,1))
b = tf.reshape(tf.range(2), (1,2))
tf.range(3),tf.range(2), a,b

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [31]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [32]:
before = id(Y)
before

2539824722512